## Base options
epochs: 60
batch_size: 64
print_freq: 100
#pretrain_path: null
pretrain_path: /home/zunzhi/PycharmProjects/ide_baseline/data/resnet50-19c8e357.pth  # specify "null" if do not use pretrained weights
img_size: !!python/tuple [384, 128]
crop_size: !!python/tuple [384, 128]
padding: 7
dataset: MSMT17
lr: !!python/float 0.1
lr_strategy: resnet_style
wd: !!python/float 5e-4
record_grad: true
view_labeled: [2, 5, 8, 9, 10, 13]
#view_labeled: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
use_cuda: true